version: '3.7'
services:
  server:
    image: "syh622/connected-42:latest"
    restart: always
    volumes:
      - appdata:/app
    ports:
      - '8081:8080'
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh postgres:5432 -t 5
        yarn start
    networks:
      - app
networks:
  app:
    driver: bridge
volumes:
  appdata:
    driver: local
