version: '3.7'
services:
  server:
    image: "syh622/connected-42"
    container_name: server
    restart: always
    volumes:
      - appdata:/app
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh postgres:5432 -t 30
        yarn start
networks:
  default:
    external:
      name: db
volumes:
  appdata:
    driver: local
