name: CI

on:
  push:
    branches:
      - master

jobs:
  cd:
    name: SSH and Deploy Code
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy Code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami