name: CI

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: E2E Tests and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install & Tests
        run: |
          npm install
          npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-connected-server
          fail_ci_if_error: true
      - name: Docker build
        run: |
          docker build -t syh622/connected-42 .
      - name: Docker push
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag syh622/connected-42 syh622/connected-42:latest
          docker tag syh622/connected-42 syh622/connected-42:${{ github.sha }}
          docker push syh622/connected-42:latest
          docker push syh622/connected-42:${{ github.sha }}