name: CI

on:
  push:
    branches:
      - master

jobs:
  cd:
    name: SSH and Deploy
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: SSH and Deploy Code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al